# Generated by Django 4.1.2 on 2022-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hokelaapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("submitted_by", models.CharField(max_length=75)),
                ("shop", models.CharField(max_length=255)),
                ("maziwa_kubwa", models.IntegerField()),
                ("maziwa_ndogo", models.IntegerField()),
                ("premimum", models.IntegerField()),
                ("daily_hope", models.IntegerField()),
                ("geocoords", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
